Create Power BI Pro Licenses.pbix
mmaclean13/action-testing pull request #7
Opened 2022-02-22 20:40 UTC by mmaclean13

test action by committing .pbix file

2022-02-22 20:48 UTC, nathangiusti requested changes
The action did not run correctly. The workflow does not contain a trigger event. 

Take a look at this: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
Let me know if you have questions.

2022-02-22 20:52 UTC, mmaclean13 commented
@nathangiusti - just updated the action to contain an **on: [pull request]** trigger. Would you please take a look?

2022-02-22 21:06 UTC, nathangiusti commented on .github/workflows/format_json.yaml
> +on: [pull request]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore

2022-02-22 21:23 UTC, nathangiusti requested changes
Still have an error. Look at the actions tab of your repo and check out the error message from the latest run and see if you can figure out the fix. If you can't ping me and we can work it out together.

2022-02-23 15:12 UTC, nathangiusti requested changes

2022-02-23 15:12 UTC, nathangiusti commented on .github/workflows/format_json.yaml
> +runs-on: ubuntu-latest
The tabbing is off, that's why it's crashing. Yaml is very white space sensitive.

You can paste your yaml here to verify that it is formatted correctly. http://www.yamllint.com/

2022-02-23 15:13 UTC, nathangiusti commented on .github/workflows/format_json.yaml
> +runs-on: ubuntu-latest
Python is also very white space sensitive so you'll need to get used to it.

2022-03-02 20:59 UTC, nathangiusti requested changes
The error has to do with the description. Check and see if it matches the way it's laid out in other workflows. I won't be able to take a look at this until tomorrow.

2022-03-02 22:17 UTC, mmaclean13 commented
It ran!

2022-03-03 15:29 UTC, nathangiusti requested changes

2022-03-03 15:29 UTC, nathangiusti commented on .github/workflows/format_json.yaml
> +#description: 'Deserializes PBIX Files into json files for easier version control'
Workflows don't have a description field. Go ahead and delete this line and we can look at deploying it to all of our repos.

2022-03-03 17:39 UTC, nathangiusti approved these changes

2022-03-03 23:34 UTC, merged